### ISSUE TITLE
Error on build with Ubuntu 20.04

### ISSUE THREAD

**Issue by S-Streit** [zlib-ng/minizip-ng#724]
JTLExt.cc: In member function 'void JTL_Ext::sendZip(Compressor*, const std::vector<CompressedTile>&, const std::vector<int>&)':
JTLExt.cc:142:35: error: too many arguments to function 'void* mz_stream_mem_create()'
  142 |   mz_stream_mem_create(&mem_stream);
      |                                   ^
In file included from JTLExt.cc:32:
../../minizip-ng/mz_strm_mem.h:37:9: note: declared here
   37 | void*   mz_stream_mem_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
JTLExt.cc:146:31: error: too many arguments to function 'void* mz_zip_writer_create()'
  146 |   mz_zip_writer_create(&handle);
      |                               ^
In file included from JTLExt.cc:35:
../../minizip-ng/mz_zip_rw.h:264:9: note: declared here
  264 | void*   mz_zip_writer_create(void);
      |         ^~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/usr/app/server/src'
make[1]: *** [Makefile:504: JTLExt.o] Error 1
make: *** [Makefile:408: all-recursive] Error 1

There seems to be an error in the function call at JTLExt.cc:142:35 since it is passed a handle reference but declaration and implementation state no input arguments
The same issue is true for JTLExt.cc:146:31

Im not sure if this is an version issue or anything else. 
I can just additionally say that the 3.0.10 build runs smoothly on the same configuration

Best Simon

**Comment by nmoinvaz** [comment]
Yes there were some breaking API changes in 4.0 if you not using compatiblity API. I posted notice for some time.
