### ISSUE TITLE
Undefined symbol error for Bcrypt

### ISSUE THREAD

**Issue by bhavyajn7599** [zlib-ng/minizip-ng#785]
I am trying to compile Minizip for Windows platform and after compilation I am using libminizip.lib in my project unresolved external symbol error for all bcrypt APIs

![Bcrypt](https://github.com/zlib-ng/minizip-ng/assets/171550500/27ca18df-382b-4a42-a838-9ca69797ab18)
  Then i ran dumpbin /SYMBOLS libminizip.lib this command for checking all the symbols and i saw that these symbols are all undefined.
![image](https://github.com/zlib-ng/minizip-ng/assets/171550500/74db681a-65e4-4614-9fbf-d3006fc0e9d3)
 This is the command I am using for compiling Minizip project I am using version 4.0.4

cmake -S . -B build -D MZ_BUILD_TESTS=ON -DZSTD_TAG=dev -D MZ_DECOMPRESS_ONLY=ON -D MZ_FORCE_FETCH_LIBS=ON -D MZ_FILE32_API=ON -D MZ_COMPRESS_ONLY=ON -D MZ_SIGNING=ON -D MZ_LIBBSD=ON -D MZ_BUILD_UNIT_TESTS=ON -D MZ_CODE_COVERAGE=ON -D MZ_ICONV=ON -DZLIB_TAG=develop -D MZ_LIBCOMP=ON -D MZ_OPENSSL=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
[Build_log.txt](https://github.com/user-attachments/files/15530843/Build_log.txt)
This the log of build. Can you check why these API's are not getting defined. 
I tried compiling with minizip 3.0.10 and in that I am not facing any errors as I can see that mz_crypt_winvista.c file was added after 3.0.10  . Can you check if that file has some issue. Or am i missing something?

**Comment by nmoinvaz** [comment]
Is it not linked with bcrypt.lib? Please include all build logs.

**Comment by bhavyajn7599** [comment]
[Build with 4.0.7.txt](https://github.com/user-attachments/files/15883225/Build.with.4.0.7.txt)
Please find attached the text file for complete build log

**Comment by bhavyajn7599** [comment]
HI Is there any update on this?

**Comment by nmoinvaz** [comment]
I was not able to reproduce your results. Consider upgrading CMake or Visual Studio. Maybe somebody else who has the same issue with come along and solve it. If you find out what is causing it please let me know.

**Comment by lucasoares** [comment]
The same is hapenning with me @nmoinvaz no idea how to fix it (I'm a newbie on cmake):

```
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptOpenAlgorithmProvider referenced in function mz_crypt_rand
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptGetProperty referenced in function mz_crypt_sha_begin
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptSetProperty referenced in function mz_crypt_aes_set_key
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptCloseAlgorithmProvider referenced in function mz_crypt_rand
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptEncrypt referenced in function mz_crypt_aes_encrypt
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptDecrypt referenced in function mz_crypt_aes_decrypt
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptImportKey referenced in function mz_crypt_aes_set_key
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptDestroyKey referenced in function mz_crypt_aes_free
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptCreateHash referenced in function mz_crypt_sha_begin
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptHashData referenced in function mz_crypt_sha_update
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptFinishHash referenced in function mz_crypt_sha_end
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptDuplicateHash referenced in function mz_crypt_hmac_copy
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptDestroyHash referenced in function mz_crypt_hmac_copy
1>minizip-ng.lib(mz_crypt_winvista.c.obj) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function mz_crypt_rand
```

**Comment by bhavyajn7599** [comment]
Hi,
So for resolving this add these lines in mz_crypt_winvista.c and then recompile minizip
I was able to resolve these errors after this
![image](https://github.com/user-attachments/assets/56370891-8280-42ad-8fe4-d737cce644f9)

**Comment by lucasoares** [comment]
> Hi, So for resolving this add these lines in mz_crypt_winvista.c and then recompile minizip I was able to resolve these errors after this ![image](https://private-user-images.githubusercontent.com/171550500/403251058-56370891-8280-42ad-8fe4-d737cce644f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NDQ1NzUsIm5iZiI6MTczNjk0NDI3NSwicGF0aCI6Ii8xNzE1NTA1MDAvNDAzMjUxMDU4LTU2MzcwODkxLTgyODAtNDJhZC04ZmU0LWQ3MzdjY2U2NDRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQxMjMxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGZmYTc0YjFlZWViYTEyNDk0N2NhMGE2Mjg4MTBkZjcxZGFjMDc0Nzc3NzQ3NzVlYzRhYjM2YTFjYjQ0OTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UiihQXMm6f0JBw4OXvtz_0KHNRuH7OWyv-LT0YTJ9Wc)

How you installed bcrypt.lib?
